repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit # repo with predefined hooks
    rev: v0.13.0 # ruff version
    hooks:
      - id: ruff-check # use predefined linter
        args: [--fix]
      - id: ruff-format # use predefined formatter
        args: [--line-length=100] # must be synced with pyproject.toml
# this pre commit package basically ensures that when we commit code,
# it is formatted and linted according to the rules defined with ruff.


  - repo: local
    hooks:
      - id: pytest
        name: Run pytest
        entry: pytest
        language: system
        types: [python]
        pass_filenames: false