name: Auto Close Rapport Issues 

on:
  issues:
    types: [labeled]

jobs:
  close_issue:
    if: github.event.label.name == 'Rapport'
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Close issue
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              state: 'closed'
            });
